# Generated by Django 2.2 on 2019-04-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play_picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('suggester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play_picture.Suggester')),
            ],
        ),
    ]
