# Generated by Django 2.2 on 2019-05-08 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('play_picture', '0004_auto_20190422_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 12, 0, 43, 500575, tzinfo=utc), verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=0),
        ),
    ]
