# Generated by Django 2.2 on 2019-05-09 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('play_picture', '0005_auto_20190508_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headPic',
            field=models.CharField(default='default_img.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 7, 1, 25, 975477, tzinfo=utc), verbose_name='birthday'),
        ),
    ]
