# Generated by Django 2.2 on 2019-05-09 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('play_picture', '0007_auto_20190509_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 7, 14, 17, 22758, tzinfo=utc), verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headPic',
            field=models.CharField(default='/img/head/default_img.png', max_length=200),
        ),
    ]
